- src/StripeWebhookCall.php
[See the method here](https://github.com/spatie/laravel-stripe-webhooks/blob/eb7845d068607081fba6a04ed2a9408872d7b1a3/src/Exceptions/WebhookFailed.php#L25). Not sure if something should be added to the changelog..
> [bugfix] Add missing param to jobClassDoesNotExist method

- composer.json
This PR adds support for latest `stripe-php` release.
No BC were found, except dropping PHP 5.3 which is not case at all for this package.
> add support for stripe-php v6

- README.md
The webhook example provided needs an additional namespace path to fit with the provided configuration file change.
I added the missing class path/directory name on the namespace of the webhook class rather than removing it from the config file, as it felt better to keep all the 'StripeWebhook' jobs together.
> Corrected namespace on example webhook

- README.md
- src/Middlewares/VerifySignature.php
- tests/Middlewares/VerifySignatureTest.php
So this is a little weird. What was actually needed here was a way to specify which secret the verify middleware would use for the request. At first I thought about [middleware parameters](https://laravel.com/docs/5.6/middleware#middleware-parameters) but the usage was not pretty.
In the end it's quite simple by adding an *optional* route param and usage is nicer with a natural mapping of webhook endpoint urls to your secrets.
If you have multiple endpoints configured in stripe you can add a matching config key with the appropriate secret e.g. with endpoints in stripe setup as `https://localhost/stripe-webhook/account` and `https://localhost/stripe-webhook/connect` you'd change config to:
```
return [
'signing_secret_account' => 'whsec_abc...',
'signing_secret_connect' => 'whsec_123...', …
```
> Adding support for multiple signing secrets #25

- README.md
Documentation previously mentioned using only `:post` when defining Stripe connect routes.  Clarified this for consistency.
> Updated documentation for multiple secrets

- src/StripeWebhooksController.php
Hi, there
I noticed that the controller is not sending anything back. 
Packages like [laravel-debugbar](https://github.com/barryvdh/laravel-debugbar) relies on response type to [inject](https://github.com/barryvdh/laravel-debugbar/blob/master/src/LaravelDebugbar.php#L618) their content along with response.
See the response in attached secreenshot. It contains the laravel debugbar styles and scripts.
There might be application level middleware that is trying to modify the response. Sending the response object back will help them to determine what type of content is being sent back.
See how Laravel Cashier is sending the response back
https://github.com/laravel/cashier/blob/be0bbad876b7510e39a7d29bc6ce9cff7a3979e4/src/Http/Controllers/WebhookController.php#L85
I know that  no one is using …
> Response back json message

- composer.json
Hi @riasvdv
Stripe has releases `stripe-php` v7.0 recently but this package does not allow to install it.
https://github.com/stripe/stripe-php/wiki/Migration-guide-for-v7
I think it is safe to allow as i dont see any changes related to Webhook.
Thanks.
> Allow stripe-php 7.x

- README.md
With out the leading `\` the following exception will get thrown:
> UnexpectedValueException
> Invalid route action: [App\Http\Controllers\Spatie\StripeWebhooks\StripeWebhooksController]
> Fixed controller path in README

- config/stripe-webhooks.php
- src/StripeSignatureValidator.php
- tests/IntegrationTest.php
It's for debugging purpose
It's awesome, safe me lot of work, 
i notice i need this when i want to simulate a webhook call from a rest client
> Option for enable or disable signature verification

- README.md
- config/stripe-webhooks.php
- src/StripeWebhookProfile.php
- src/StripeWebhooksController.php
- tests/IntegrationTest.php
This PR implements issue https://github.com/spatie/laravel-stripe-webhooks/issues/86.
I've added a new default `StripeWebhookProfile` class that determines if a webhook event was already processed before. If it was, the event will not be processed again.
You can also override that class in the config. This can be useful if you want to do add some additional logic to determine if an event should be processed or not.
> Only process events once

- src/StripeWebhooksServiceProvider.php
Hi,
v3.0 introduce a breaking change that is not backward campatible.
When there is namespace specified in Laravel skeleton, the routing does not work.
Steps to reproduce
```php
<?php
namespace App\Providers;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
class RouteServiceProvider extends ServiceProvider
{
// prefix the route in good old way
protected $namespace = 'App\\Http\\Controllers';
}
```
Now define the route like this, by using macro
```php
// routes/web.php
<?php
// Stripe Webhooks
Route::group(['prefix' => 'webhooks/stripe', 'as' => 'webhooks.stripe.'], function () {
Route::stripeWebhooks('/')->name('main');
});
```
This PR restores the routing back to as it used to be in …
> Fix routing

- CHANGELOG.md
This PRs adds an unreleased heading to the Changelog so that the [`changelog-updater-action`](https://github.com/spatie/laravel-stripe-webhooks/commit/50aacf59ef884848b117b8f1ab8f36196ef590bd) works as expected. (The Action needs that heading to know, where to place the relases notes)
See our Twitter discusssion: https://twitter.com/freekmurze/status/1456587699184340995
(The compare URL already uses the latest version 3.1.0 so that it would work correctly on the next release. You should update that URL to use 3.0.0 if you want to retry the Action somehow)
> Add Unreleased Heading to Changelog

- UPGRADING.md
New columns must be nullable, since the table may have existing records
> docs: fix upgrade guide

- README.md
- config/stripe-webhooks.php
- src/StripeWebhooksController.php
Hello :wave: 
On the back of looking at your [spatie/laravel-webhook-client](https://github.com/spatie/laravel-webhook-client) package, I was looking at this as an example implementation and believe there may be a couple of minor mistakes.
Please consider this PR as a potential fix.
> Corrected potential WebhookConfig issues.

- README.md
- config/stripe-webhooks.php
- src/StripeWebhookProfile.php
- tests/IntegrationTest.php
Hi, @freekmurze 
Re-submission of PR https://github.com/spatie/laravel-stripe-webhooks/pull/87
Previous PR was [reverted](https://github.com/spatie/laravel-stripe-webhooks/pull/89) because the query `where("payload->id")` was not working on PostgreSQL.
The `payload` column was type of `text`, but in [newer](https://github.com/spatie/laravel-webhook-client/blob/main/database/migrations/create_webhook_calls_table.php.stub#L16) version it is `JSON` type
And now query is well supported by all databases
https://laravel.com/docs/8.x/queries#json-where-clauses
I did nothing special in this PR, imported changes from original PR. :)
cc @aerni
> feat: process webhook once

- src/StripeWebhookProfile.php
Hi,
There might be other type of webhooks being stored in `webhook_calls` table, for example mailcoach is storing `ses-feedback` webhooks.
This PR scope the SQL query to only search for `stripe` webhooks while checking for duplicates.
Thanks.
> fix: only check for stripe webhooks

- UPGRADING.md
For anyone upgrading from v2 to v3, this change is required because e.g. https://github.com/spatie/laravel-stripe-webhooks/blob/main/src/StripeWebhookProfile.php uses a json operator on the payload column.
> UPGRADING.md v3: Add payload column type change

- README.md
- config/stripe-webhooks.php
- src/ProcessStripeWebhookJob.php
- tests/StripeWebhookCallTest.php
ref #127 
I didn't introduce a default job class within the package is because that might need involve adding a new laravel package for the queue, so using this simple approach first and let user do the customization.
> let user able to define a default job as a catchall event handler

- README.md
This PR adds documentation to assist developers in transforming the `WebhookCall` payload into Stripe objects.
> Add docs for transforming `WebhookCall` payload into Stripe object

- composer.json
Hi,
v9 has been released recently, i dont see any breaking change regarding webhook except some constants which are not being used by this package.
https://github.com/stripe/stripe-php/blob/master/CHANGELOG.md#900---2022-08-02
> allow stripe sdk v9
